Repository ruamk/carma, pull requests merged in 2019-03, with the labels that each got.

#20 Release 04.03.2019
  srv/resources/assets/script/screens/dictionaries.coffee
Labels: bug

#21 Release 17.03.2019
  README.md
  carma-nominatim-mediator/src/Carma/NominatimMediator/Types.hs
Labels: enhancement

#22 Release 22.03.2019
  caroperator-svc/LICENSE
  caroperator-svc/Main.hs
  caroperator-svc/README.md
  caroperator-svc/cert.sh
  caroperator-svc/install.sh
Labels: bug, enhancement

#24 Feature/check contract
  carma-models/src/Carma/Model/VinFormat.hs
  carma-models/src/Carma/Model/VinFormat/Meta.hs
  tools/vinnie/src/Carma/VIN.hs
  tools/vinnie/src/Carma/VIN/SQL.hs
Labels: enhancement
