Repository ruamk/carma, pull requests merged in 2021-04, with the labels that each got.

#150 Release 2021.04.12
  carma-casepartner-fe/book/docs/current_cases.md
  carma-casepartner-fe/book/docs/images/case_page.png
  carma-casepartner-fe/book/docs/images/case_page_with_driver.png
  carma-casepartner-fe/book/docs/images/cases_to_close.png
  carma-casepartner-fe/book/docs/images/choosing_a_driver.png
  carma-casepartner-fe/book/docs/images/closing_case.png
  carma-casepartner-fe/book/docs/images/current_cases.png
  carma-casepartner-fe/book/docs/images/finish_the_service.png
  carma-casepartner-fe/book/docs/images/fixing_late.png
  carma-casepartner-fe/book/docs/images/in_progress.png
  carma-casepartner-fe/book/docs/images/login.png
  carma-casepartner-fe/book/docs/images/search.png
  carma-casepartner-fe/book/docs/images/the_second_page_of_cases.png
  carma-casepartner-fe/book/docs/index.md
  carma-casepartner-fe/book/docs/searching_for_cases.md
  carma-casepartner-fe/book/docs/working_with_case.md
  carma-casepartner-fe/book/mkdocs.yml
  carma-casepartner-fe/package.json
  carma-casepartner-fe/public/map-client.html
  carma-casepartner-fe/src/Global.elm
  carma-casepartner-fe/src/Pages/Instruction.elm
  carma-casepartner-fe/src/Pages/Search.elm
  carma-casepartner-fe/src/Pages/Services.elm
  carma-casepartner-fe/src/Pages/Settings.elm
  carma-casepartner-fe/src/Pages/ShowService.elm
  carma-casepartner-fe/src/Ui.elm
  carma-casepartner-fe/src/Utils.elm
  carma-casepartner-us/src/AppHandlers/Service.hs
  carma-casepartner-us/src/Site.hs
  location-sharing-svc/package-lock.json
  srv/resources/assets/elm/photos-in-carma/elm.json
  srv/resources/assets/elm/photos-in-carma/package-lock.json
  srv/resources/assets/elm/photos-in-carma/package.json
  srv/resources/assets/elm/photos-in-carma/src/Api.elm
  srv/resources/assets/elm/photos-in-carma/src/ElmPhotos.elm
  srv/resources/assets/elm/photos-in-carma/src/Types.elm
  srv/resources/assets/script/screens/case.coffee
  srv/resources/assets/template/fields/form.pug
  srv/snaplets-default/proxy/devel.cfg
  srv/src/Application.hs
  srv/src/ApplicationInit.hs
  srv/src/Snaplet/Proxy.hs
  tools/builder.sh
Labels: delivered-to-production

#153 Add new fields to Partner model: isPartner, legalName and inn.
  carma-models/src/Carma/Model/Partner.hs
  carma-models/src/Carma/Model/Partner/Persistent.hs
  database/patches/1.360.0-new-partner-fields.sql
  srv/resources/assets/script/screens/partners.coffee
Labels: enhancement

#152 Feature/view photos in carma
  srv/package-lock.json
  srv/package.json
  srv/resources/assets/script/screens/case.coffee
  srv/resources/assets/template/fields/form.pug
  srv/webpack.config.coffee
  tools/builder.sh
Labels: bug

#154 Release 2012.04.14
  carma-models/src/Carma/Model/Partner.hs
  carma-models/src/Carma/Model/Partner/Persistent.hs
  database/patches/1.360.0-new-partner-fields.sql
  srv/package-lock.json
  srv/package.json
  srv/resources/assets/script/screens/case.coffee
  srv/resources/assets/script/screens/partners.coffee
  srv/resources/assets/template/fields/form.pug
  srv/webpack.config.coffee
  tools/builder.sh
Labels: bug, delivered-to-production, dependencies, enhancement

#160 Release 2012.04.26
  carma-casepartner-fe/src/Api.elm
  carma-casepartner-fe/src/Pages/Search.elm
  carma-casepartner-fe/src/Pages/Services.elm
  carma-casepartner-fe/src/Pages/ShowService.elm
  carma-casepartner-fe/src/Types.elm
  carma-casepartner-fe/src/Ui.elm
  carma-casepartner-fe/src/Utils.elm
  carma-casepartner-us/src/AppHandlers/MobileAPI.hs
  carma-casepartner-us/src/AppHandlers/Service.hs
  carma-models/src/Carma/Model/Partner.hs
  carma-models/src/Carma/Model/Partner/Persistent.hs
  database/patches/1.360.1-partner-field-code1c.sql
  srv/src/Triggers/Action/SMS.hs
Labels: delivered-to-production, enhancement

#161 Feature/casepartner backend refactoring
  carma-casepartner-us/src/AppHandlers/MobileAPI.hs
  carma-casepartner-us/src/Util.hs
  carma-utils/package.yaml
  carma-utils/src/Carma/Utils/Log.hs
  carma-utils/src/Carma/Utils/Snap.hs
  srv/src/AppHandlers/RKC.hs
  srv/src/Snaplet/Search/Utils.hs
  srv/src/Util.hs
Labels: enhancement
